<?php
/**
* Implementation of hook_menu()
* 
*/
function nodejschat_field_menu() {
  $items = array();
  $items['admin/settings/nodejschat_field'] = array(
    'title' => t('NodeJS Chat Server Configuration'),
    'description' => t('Configuration for the Node.js Chat API module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodejschat_field_configuration_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['nodejschat_field/save/connection'] = array(
    'page callback' => 'nodejschat_field_save_connection',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
/**
* NodeJS Chat Configuration Form
* 
* @param mixed $form_state
*/
function nodejschat_field_configuration_form(&$form_state) {
  $form['nodejschat_field_chatserverurl'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('nodejschat_field_chatserverurl', ''),
    '#title' => t('Node.JS Chat Server URL'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
/**
* Trimming Spaces in form_validate()
* 
* @param mixed $form
* @param string $form_state
*/
function nodejschat_field_configuration_form_validate($form, &$form_state) {
  $form_state['values']['nodejschat_field_chatserver'] = trim($form_state['values']['nodejschat_field_chatserver']);
}
